var verbs = [
    {
       'infinitive':'be',
       'past':'was/where',
       'participle':'been'        
    },
    {
        'infinitive':'beat',
        'past':'beat',
        'participle':'beaten'        
     },
    {
        'infinitive':'do',
        'past':'did',
        'participle':'done'        
     },
     {
        'infinitive':'drive',
        'past':'drover',
        'participle':'driven'        
     },{
        'infinitive':'a1',
        'past':'a2',
        'participle':'a3'        
     },
     {
        'infinitive':'b1',
        'past':'b2',
        'participle':'b3'        
     },
     {
        'infinitive':'c1',
        'past':'c2',
        'participle':'c3'        
     },
     {
        'infinitive':'d1',
        'past':'d2',
        'participle':'d3'        
     },
     {
        'infinitive':'e1',
        'past':'e2',
        'participle':'e3'        
     }
]